src/App.css, src/App.js, src/components/DownButton.js, src/components/Header.js, src/components/MainViewContainer.js, src/components/SelectType.js, src/components/UpButton.js, yarn.lock
* material ui ve css fixes
* hot-fix
=> Materialui react (#8)

AcikKaynakPrKilavuzu.md
=> Ana Repoya PR Açma Klavuzu

src/components/MainViewContainer.js
=> filter view fix

src/components/ListPage.js, src/components/MainViewContainer.js
fixed [#24](https://github.com/acikkaynak/eczane-frontend/issues/24)
=> Phone icon control

src/components/MainViewContainer.js
fixed [#24](https://github.com/acikkaynak/eczane-frontend/issues/24)
=> hide phone icon in map when phone is not exist

src/components/MainViewContainer.js
title was static as 'Eczane' for both options. 
it is fixed to work dynamically
=> fix: list view title problem fixed.

src/components/ListPage.js
Redirected changes to new ListPage component.
=> additional commit for #26

src/components/Header/HeaderCombined.js, src/components/Header/HeaderRow.js, src/components/Header/SearchBar.js, src/components/MainViewContainer.js
1- Type filtering ->Eczane - Hastane -Veteriner
2- Search bar -> District'te adres'te isim'de arama yapar
3- Sehir -> Sadece liste view'da calisir. Sehre gore filtreler.
=> 3 Filtering Functionality Added

src/App.css, src/components/MainViewContainer.js
=> add loading spinner

public/left-icon.svg, src/App.css, src/components/Footer/Footer.js, src/components/Footer/style.css, src/components/MainViewContainer.js
Footer'ın styling düzeltmeleri ve district filtering eklenmesi
=> Footer işlevlik ve styling

src/components/Header/HeaderCombined.js, src/components/Header/HeaderRow.js, src/components/MainViewContainer.js
Static olarak implement edilmişti. Veteriner datası geldiği anda dinamik olarak sağlayacak bunu.
=> Veteriner butonu data olduğunda disabled'ı kaldıracak dinamik olarak.

src/components/InfoCard.js
Adres alanina detay goruntuleme eklendi ve popup iconlarina subType s…
=> Adres alanina detay Eklendi ve Icon subType eklendi

src/App.css, src/components/MainViewContainer/MainViewContainer.js
css dosyasi gerekli paketin. muhtemelen tiklandigini anlamiyor eski durumda
=> Fullscreen Butonu Mobilde Fix

src/components/Footer/Footer.js, src/components/Footer/Footer.module.scss
=> fixed city buttons nesting

src/App.css, src/components/Header/HeaderCombined.js, src/components/InfoCard/InfoCard.module.scss, src/components/ListPage/ListPage.module.scss, src/components/MainViewContainer/MainViewController.styled.js
- cardlar border-radius ve gap
- desktop bg-iamge asagi yaslandi tam ekran
=> Styling fix'leri

src/components/MainViewContainer/MainViewContainer.js, src/components/MainViewContainer/MainViewContainer.module.scss
MainViewContainer components has scss file for now, removed styled components
=> MainViewContainer components has scss file for now

.eslintrc.yml, package-lock.json, package.json, src/components/DragIcon/DragIcon.js, src/components/Footer/Footer.js, src/components/Header/HeaderCombined.js, src/components/Header/HeaderRow.js, src/components/Header/SearchBar.js, src/components/InfoCard/InfoCard.js, src/components/ListPage/ListPage.js, src/components/MainViewContainer/MainViewContainer.js, src/lib/Block/Block.js, src/lib/Spacer.js
=> Eslint eklendi.

src/components/Others/Others.js, src/components/Others/Others.module.scss
=> tooltipler state den css e dönüştürüldü.

src/components/Footer/Footer.js, src/components/MainViewContainer/MainViewContainer.js, src/components/MainViewContainer/MainViewContainer.module.scss, src/components/MapMarkerCluster/MapMarkerCluster.js, src/components/MapPage/MapPage.js, src/components/MapPage/MapPage.module.scss, src/utils/generalFunctions.js
=> Mainview refactor edildi

src/components/MapPage/MapPage.js
mapViscosity: 1 -> haritanın dışarı taşıp geri gelmesini engelliyor.
preferCanvas -> haritayı canvas'a basıyor
=> Map Options
